export const BOSSES = {
  boss: {
    sheet: "skeletonBoss",
    crop: { x: 70, y: 95, width: 165, height: 195 },
    health: 12,
    speed: 58,
    damageCooldown: 850,
    aiStyle: "boss",
    desiredRange: 185,
    retreatHealthRatio: 0,
    retreatChance: 0,
    tint: 0xffd1f1,
  },
  infernalBoss: {
    health: 16,
    speed: 72,
    damageCooldown: 780,
    aiStyle: "infernalBoss",
    desiredRange: 210,
    retreatHealthRatio: 0,
    retreatChance: 0,
    projectileCooldown: 1600,
    superProjectileCooldown: 4200,
    superAttackChance: 0.45,
    tint: 0xffffff,
  },
  frostTyrant: {
    health: 18,
    speed: 62,
    damageCooldown: 880,
    aiStyle: "frostTyrant",
    desiredRange: 220,
    retreatHealthRatio: 0,
    retreatChance: 0,
    projectileCooldown: 1700,
    superProjectileCooldown: 4300,
    superAttackChance: 0.46,
    tint: 0xffffff,
  },
  matriarchSoul: {
    health: 25,
    speed: 0,
    damageCooldown: 1200,
    aiStyle: "matriarchSoul",
    desiredRange: 240,
    retreatHealthRatio: 0,
    retreatChance: 0,
    projectileCooldown: 2400,
    superProjectileCooldown: 5600,
    superAttackChance: 0.45,
    tint: 0xffffff,
  },
 };
