export const ENEMIES = {
  skeleton: {
    sheet: "skeletonCommon",
    crop: { x: 270, y: 95, width: 95, height: 145 },
    health: 2,
    speed: 82,
    damageCooldown: 950,
    aiStyle: "cautious",
    desiredRange: 72,
    retreatHealthRatio: 0.35,
    retreatChance: 0.45,
    tint: 0xffffff,
  },
  guard: {
    sheet: "skeletonStrong",
    crop: { x: 820, y: 92, width: 105, height: 150 },
    health: 3,
    speed: 66,
    damageCooldown: 1050,
    aiStyle: "guard",
    desiredRange: 58,
    retreatHealthRatio: 0.25,
    retreatChance: 0.28,
    tint: 0xd6c0ff,
  },
  dog: {
    sheet: "skeletonDog",
    crop: { x: 250, y: 100, width: 125, height: 115 },
    health: 1.5,
    speed: 125,
    damageCooldown: 780,
    aiStyle: "skirmisher",
    desiredRange: 84,
    retreatHealthRatio: 0.45,
    retreatChance: 0.68,
    lungeChance: 0.32,
    tint: 0xfff1c2,
  },
  dogStrong: {
    sheet: "skeletonDogStrong",
    crop: { x: 250, y: 100, width: 125, height: 115 },
    health: 2.4,
    speed: 138,
    damageCooldown: 720,
    aiStyle: "skirmisher",
    desiredRange: 88,
    retreatHealthRatio: 0.42,
    retreatChance: 0.58,
    lungeChance: 0.42,
    tint: 0xd4b7ff,
  },
  impLittle: {
    health: 1.6,
    speed: 148,
    damageCooldown: 720,
    aiStyle: "skirmisher",
    desiredRange: 78,
    retreatHealthRatio: 0.32,
    retreatChance: 0.42,
    lungeChance: 0.46,
    superAttackChance: 0.35,
    tint: 0xffffff,
  },
  hellKiller: {
    health: 2.4,
    speed: 104,
    damageCooldown: 860,
    aiStyle: "ranged",
    desiredRange: 220,
    retreatHealthRatio: 0.38,
    retreatChance: 0.58,
    lungeChance: 0.1,
    projectileCooldown: 2800,
    superProjectileCooldown: 6800,
    superAttackChance: 0.24,
    tint: 0xffffff,
  },
  hellGolem: {
    health: 3.4,
    speed: 76,
    damageCooldown: 980,
    aiStyle: "guard",
    desiredRange: 70,
    retreatHealthRatio: 0.22,
    retreatChance: 0.2,
    lungeChance: 0.24,
    superAttackChance: 0.26,
    tint: 0xffffff,
  },
  hellTank: {
    health: 4.4,
    speed: 58,
    damageCooldown: 1080,
    aiStyle: "guard",
    desiredRange: 62,
    retreatHealthRatio: 0.15,
    retreatChance: 0.1,
    lungeChance: 0.2,
    superAttackChance: 0.34,
    tint: 0xffffff,
  },
  hellTitan: {
    health: 5.4,
    speed: 64,
    damageCooldown: 1160,
    aiStyle: "guard",
    desiredRange: 74,
    retreatHealthRatio: 0.18,
    retreatChance: 0.12,
    lungeChance: 0.28,
    superAttackChance: 0.42,
    tint: 0xffffff,
  },
  frostBladeWarrior: {
    health: 2.8,
    speed: 92,
    damageCooldown: 880,
    aiStyle: "cautious",
    desiredRange: 62,
    retreatHealthRatio: 0.25,
    retreatChance: 0.18,
    lungeChance: 0.18,
    superAttackChance: 0.22,
    tint: 0xffffff,
  },
  frostPriest: {
    health: 2.2,
    speed: 54,
    damageCooldown: 1160,
    aiStyle: "icyMage",
    desiredRange: 260,
    retreatHealthRatio: 0.42,
    retreatChance: 0.7,
    projectileCooldown: 2400,
    superProjectileCooldown: 10000,
    superAttackChance: 0.18,
    tint: 0xffffff,
  },
  frozenKnight: {
    health: 4,
    speed: 66,
    damageCooldown: 980,
    aiStyle: "guard",
    desiredRange: 58,
    retreatHealthRatio: 0.16,
    retreatChance: 0.08,
    blockChance: 0.18,
    lungeChance: 0.14,
    superAttackChance: 0.26,
    tint: 0xffffff,
  },
  iceAxeTitan: {
    health: 5.8,
    speed: 58,
    damageCooldown: 1220,
    aiStyle: "icyTitan",
    desiredRange: 68,
    retreatHealthRatio: 0.12,
    retreatChance: 0.08,
    lungeChance: 0.1,
    superAttackChance: 0.36,
    chargeCooldown: 20000,
    tint: 0xffffff,
  },
  icebladeMaster: {
    health: 2.7,
    speed: 152,
    damageCooldown: 700,
    aiStyle: "icyHunter",
    desiredRange: 74,
    retreatHealthRatio: 0.28,
    retreatChance: 0.25,
    lungeChance: 0.55,
    superAttackChance: 0.5,
    tint: 0xffffff,
  },
  iceWraith: {
    health: 2.6,
    speed: 88,
    damageCooldown: 980,
    aiStyle: "icyWraith",
    desiredRange: 225,
    retreatHealthRatio: 0.38,
    retreatChance: 0.55,
    projectileCooldown: 3600,
    superProjectileCooldown: 7200,
    superAttackChance: 0.28,
    tint: 0xffffff,
  },
 };
