export const HEROES = {
  nox: {
    id: "nox",
    name: "Nox",
    price: 0,
    description: "Remodeled void mage with animated magic attacks.",
  },
  riven: {
    id: "riven",
    name: "Riven",
    price: 0,
    description: "Remodeled blade fighter with animated slash chains and dagger projectiles.",
  },
};

export const PLAYER_BASE_STATS = {
  speed: 210,
  attackDamage: 1,
  attackCooldown: 420,
  attackRange: 92,
  critChance: 0.05,
  critMultiplier: 1.75,
  burnChance: 0,
  burnDamage: 0,
  burnDamageMultiplier: 1,
  burnDurationBonus: 0,
  dodgeChance: 0,
  projectileDodgeChance: 0,
  enemySlowOnHit: 0,
  enemySlowDuration: 0,
  blueHeartDropChance: 0,
  poisonChance: 0,
  poisonDamage: 0,
  poisonDamageReduction: 0,
  chillChance: 0,
  chillSlow: 0.15,
  chillDuration: 3000,
  fireCards: 0,
  blueHeartCards: 0,
  critCards: 0,
  poisonCards: 0,
  iceCards: 0,
  shieldEcho: false,
  crystalBlood: false,
  shieldPulse: false,
  azureBarrier: false,
  hellfireCore: false,
  infernalDash: false,
  burningWave: false,
  flameCrit: false,
  ashExplosion: false,
  infernoChain: false,
  huntersMark: false,
  sharpRitual: false,
  executionFang: false,
  killerTempo: false,
  perfectStrike: false,
  toxicReward: false,
  plagueCloud: false,
  venomRitual: false,
  spreadingPlague: false,
  blackVenom: false,
  iceBreaker: false,
  frozenGuard: false,
  crystalStep: false,
  frostNova: false,
  frostNovaDamageRatio: 0.15,
  winterHeart: false,
  deepChill: false,
  frozenShatter: false,
  shatterCritical: false,
  crystalBarrier: false,
  steamBurst: false,
  numbingVenom: false,
  frozenAfterimage: false,
  quickHandsKillTempo: false,
  potionHealMultiplier: 1,
  skillCooldown: 4500,
  rollCooldown: 900,
  rollSpeed: 520,
  rollDuration: 220,
};

export const HERO_SHOP_SKILLS = {
  nox: {
    id: "traveler-nox-void-barrage",
    title: "Void Barrage",
    description: "LMB fires Nox magic bolts; every third shot adds an arcane orb and E launches crystal shards",
    asset: "traveler2",
  },
  riven: {
    id: "traveler-riven-ember-blade",
    title: "Ember Blade",
    description: "Riven awakens Super Attack, fires dagger follow-ups, and every third projectile becomes a larger blade arc",
    asset: "traveler2",
  },
};
